import type { Metadata } from "next";
import { Providers } from "./_store/_providers/Providers";

import "./_styles/globals.css";
import { Inter } from "next/font/google";
import { DarkModeProvider } from "./_store/_contexts/DarkModeContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkModeProvider>
          <Providers>{children}</Providers>
        </DarkModeProvider>
      </body>
    </html>
  );
}
